class User(db.Model):
    # ... existing fields ...
    reset_code = db.Column(db.String(8), unique=True, nullable=True)
    reset_code_timestamp = db.Column(db.DateTime, nullable=True)
    # ... existing code ... 